[package]
name = "dds-fs-ntfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
dds-core.workspace = true
dds-fs-common.workspace = true
dds-wish-match.workspace = true
thiserror.workspace = true
chrono.workspace = true

[dev-dependencies]
zstd = "0.13"
serde_json = { workspace = true }
sha2 = { workspace = true }
