[package]
name = "dds-case-manager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
chrono.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
dds-core.workspace = true
dds-wish-match.workspace = true

[dev-dependencies]
tempfile.workspace = true
